import { Component, OnInit } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms'
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit{
  questionnaireForm: UntypedFormGroup;
  sections:any;
constructor(
    public fb:UntypedFormBuilder
){

}
ngOnInit(){
    this.questionnaireForm = this.fb.group({});
    this.sections = [{
      "code": "D1C1",
      "questions": [
          {
              "_id": "",
              "question": "",
              "isCompleted": "",
              "showRemarks": "",
              "options": "",
              "sliderOptions": "",
              "children": "",
              "questionGroup": "",
              "fileName": "",
              "instanceQuestions": "",
              "isAGeneralQuestion": "",
              "autoCapture": "",
              "allowAudioRecording": "",
              "prefillFromEntityProfile": "",
              "entityFieldName": "",
              "isEditable": "",
              "showQuestionInPreview": "",
              "deleted": "",
              "remarks": "",
              "value": "",
              "usedForScoring": "",
              "questionType": "",
              "canBeNotApplicable": "",
              "visibleIf": "",
              "validation": "",
              "externalId": "",
              "tip": "",
              "hint": "",
              "responseType": "pageQuestions",
              "modeOfCollection": "",
              "accessibility": "",
              "rubricLevel": "",
              "sectionHeader": "",
              "page": "p1",
              "questionNumber": "",
              "updatedAt": "",
              "createdAt": "",
              "__v": "",
              "createdFromQuestionId": "",
              "evidenceMethod": "",
              "payload": "",
              "startTime": "",
              "endTime": "",
              "gpsLocation": "",
              "file": "",
              "pageQuestions": [
                  {
                      "_id": "649c14e75c81330008b7e73a",
                      "question": [
                          "Name",
                          "नाम"
                      ],
                      "isCompleted": false,
                      "showRemarks": false,
                      "options": [],
                      "sliderOptions": [],
                      "children": [],
                      "questionGroup": [
                          "A1"
                      ],
                      "fileName": [],
                      "instanceQuestions": [],
                      "isAGeneralQuestion": false,
                      "autoCapture": false,
                      "allowAudioRecording": false,
                      "prefillFromEntityProfile": false,
                      "entityFieldName": "",
                      "isEditable": true,
                      "showQuestionInPreview": false,
                      "deleted": false,
                      "remarks": "",
                      "value": "",
                      "usedForScoring": "",
                      "questionType": "auto",
                      "canBeNotApplicable": "false",
                      "visibleIf": "",
                      "validation": {
                          "required": true
                      },
                      "externalId": "Q1_1687950555455-1687950567516",
                      "tip": "",
                      "hint": "",
                      "responseType": "text",
                      "modeOfCollection": "onfield",
                      "accessibility": "No",
                      "rubricLevel": "",
                      "sectionHeader": "",
                      "page": "p1",
                      "questionNumber": "1",
                      "updatedAt": "2023-06-28T11:09:27.614Z",
                      "createdAt": "2023-06-28T11:09:25.831Z",
                      "__v": 0,
                      "createdFromQuestionId": "649c14e55c81330008b7e5f4",
                      "evidenceMethod": "D1_1687950555455",
                      "payload": {
                          "criteriaId": "649c14e75c81330008b7e79c",
                          "responseType": "text",
                          "evidenceMethod": "D1_1687950555455",
                          "rubricLevel": ""
                      },
                      "startTime": 1694157617079,
                      "endTime": "",
                      "gpsLocation": "",
                      "file": ""
                  },
                  {
                      "_id": "649c14e75c81330008b7e73b",
                      "question": [
                          "Date of Birth",
                          "जन्म की तिथि"
                      ],
                      "isCompleted": false,
                      "showRemarks": false,
                      "options": [],
                      "sliderOptions": [],
                      "children": [],
                      "questionGroup": [
                          "A1"
                      ],
                      "fileName": [],
                      "instanceQuestions": [],
                      "isAGeneralQuestion": false,
                      "autoCapture": false,
                      "allowAudioRecording": false,
                      "prefillFromEntityProfile": false,
                      "entityFieldName": "",
                      "isEditable": true,
                      "showQuestionInPreview": false,
                      "deleted": false,
                      "remarks": "",
                      "value": "",
                      "usedForScoring": "",
                      "questionType": "auto",
                      "canBeNotApplicable": "false",
                      "visibleIf": "",
                      "validation": {
                          "required": true,
                          "max": "",
                          "min": ""
                      },
                      "dateFormat": "DD-MM-YYYY",
                      "externalId": "Q2_1687950555455-1687950567517",
                      "tip": "",
                      "hint": "",
                      "responseType": "date",
                      "modeOfCollection": "onfield",
                      "accessibility": "No",
                      "rubricLevel": "",
                      "sectionHeader": "",
                      "page": "p1",
                      "questionNumber": "2",
                      "updatedAt": "2023-06-28T11:09:27.614Z",
                      "createdAt": "2023-06-28T11:09:25.846Z",
                      "__v": 0,
                      "createdFromQuestionId": "649c14e55c81330008b7e5fa",
                      "evidenceMethod": "D1_1687950555455",
                      "payload": {
                          "criteriaId": "649c14e75c81330008b7e79c",
                          "responseType": "date",
                          "evidenceMethod": "D1_1687950555455",
                          "rubricLevel": ""
                      },
                      "startTime": 1694157617090,
                      "endTime": "",
                      "gpsLocation": "",
                      "file": ""
                  },
                  {
                      "_id": "649c14e75c81330008b7e73c",
                      "question": [
                          "Gender",
                          "लिंग"
                      ],
                      "isCompleted": false,
                      "showRemarks": false,
                      "options": [
                          {
                              "value": "R1",
                              "label": "Male / पुरुष",
                              "score": 0
                          },
                          {
                              "value": "R2",
                              "label": "Female / महिला",
                              "score": 0
                          }
                      ],
                      "sliderOptions": [],
                      "children": [],
                      "questionGroup": [
                          "A1"
                      ],
                      "fileName": [],
                      "instanceQuestions": [],
                      "isAGeneralQuestion": false,
                      "autoCapture": false,
                      "allowAudioRecording": false,
                      "prefillFromEntityProfile": false,
                      "entityFieldName": "",
                      "isEditable": true,
                      "showQuestionInPreview": false,
                      "deleted": false,
                      "remarks": "",
                      "value": "",
                      "usedForScoring": "",
                      "questionType": "auto",
                      "canBeNotApplicable": "false",
                      "visibleIf": "",
                      "validation": {
                          "required": true
                      },
                      "externalId": "Q3_1687950555455-1687950567518",
                      "tip": "",
                      "hint": "",
                      "responseType": "radio",
                      "modeOfCollection": "onfield",
                      "accessibility": "No",
                      "rubricLevel": "",
                      "sectionHeader": "",
                      "page": "p1",
                      "questionNumber": "3",
                      "updatedAt": "2023-06-28T11:09:27.614Z",
                      "createdAt": "2023-06-28T11:09:25.860Z",
                      "__v": 0,
                      "createdFromQuestionId": "649c14e55c81330008b7e600",
                      "evidenceMethod": "D1_1687950555455",
                      "payload": {
                          "criteriaId": "649c14e75c81330008b7e79c",
                          "responseType": "radio",
                          "evidenceMethod": "D1_1687950555455",
                          "rubricLevel": ""
                      },
                      "startTime": 1694157617101,
                      "endTime": "",
                      "gpsLocation": "",
                      "file": ""
                  },
                  {
                      "_id": "649c14e75c81330008b7e73d",
                      "question": [
                          "Educational Qualification",
                          "शैक्षिक योग्यता"
                      ],
                      "isCompleted": false,
                      "showRemarks": false,
                      "options": [],
                      "sliderOptions": [],
                      "children": [],
                      "questionGroup": [
                          "A1"
                      ],
                      "fileName": [],
                      "instanceQuestions": [],
                      "isAGeneralQuestion": false,
                      "autoCapture": false,
                      "allowAudioRecording": false,
                      "prefillFromEntityProfile": false,
                      "entityFieldName": "",
                      "isEditable": true,
                      "showQuestionInPreview": false,
                      "deleted": false,
                      "remarks": "",
                      "value": "",
                      "usedForScoring": "",
                      "questionType": "auto",
                      "canBeNotApplicable": "false",
                      "visibleIf": "",
                      "validation": {
                          "required": true
                      },
                      "externalId": "Q4_1687950555455-1687950567519",
                      "tip": "",
                      "hint": "",
                      "responseType": "text",
                      "modeOfCollection": "onfield",
                      "accessibility": "No",
                      "rubricLevel": "",
                      "sectionHeader": "",
                      "page": "p1",
                      "questionNumber": "4",
                      "updatedAt": "2023-06-28T11:09:27.614Z",
                      "createdAt": "2023-06-28T11:09:25.872Z",
                      "__v": 0,
                      "createdFromQuestionId": "649c14e55c81330008b7e606",
                      "evidenceMethod": "D1_1687950555455",
                      "payload": {
                          "criteriaId": "649c14e75c81330008b7e79c",
                          "responseType": "text",
                          "evidenceMethod": "D1_1687950555455",
                          "rubricLevel": ""
                      },
                      "startTime": 1694157617107,
                      "endTime": "",
                      "gpsLocation": "",
                      "file": ""
                  },
                  {
                      "_id": "649c14e75c81330008b7e73e",
                      "question": [
                          "Current Post",
                          "वर्तमान पद"
                      ],
                      "isCompleted": false,
                      "showRemarks": false,
                      "options": [],
                      "sliderOptions": [],
                      "children": [],
                      "questionGroup": [
                          "A1"
                      ],
                      "fileName": [],
                      "instanceQuestions": [],
                      "isAGeneralQuestion": false,
                      "autoCapture": false,
                      "allowAudioRecording": false,
                      "prefillFromEntityProfile": false,
                      "entityFieldName": "",
                      "isEditable": true,
                      "showQuestionInPreview": false,
                      "deleted": false,
                      "remarks": "",
                      "value": "",
                      "usedForScoring": "",
                      "questionType": "auto",
                      "canBeNotApplicable": "false",
                      "visibleIf": "",
                      "validation": {
                          "required": true
                      },
                      "externalId": "Q5_1687950555455-1687950567519",
                      "tip": "",
                      "hint": "",
                      "responseType": "text",
                      "modeOfCollection": "onfield",
                      "accessibility": "No",
                      "rubricLevel": "",
                      "sectionHeader": "",
                      "page": "p1",
                      "questionNumber": "5",
                      "updatedAt": "2023-06-28T11:09:27.614Z",
                      "createdAt": "2023-06-28T11:09:25.885Z",
                      "__v": 0,
                      "createdFromQuestionId": "649c14e55c81330008b7e60c",
                      "evidenceMethod": "D1_1687950555455",
                      "payload": {
                          "criteriaId": "649c14e75c81330008b7e79c",
                          "responseType": "text",
                          "evidenceMethod": "D1_1687950555455",
                          "rubricLevel": ""
                      },
                      "startTime": 1694157617110,
                      "endTime": "",
                      "gpsLocation": "",
                      "file": ""
                  }
              ]
          },
          {
              "_id": "",
              "question": "",
              "isCompleted": "",
              "showRemarks": "",
              "options": "",
              "sliderOptions": "",
              "children": "",
              "questionGroup": "",
              "fileName": "",
              "instanceQuestions": "",
              "isAGeneralQuestion": "",
              "autoCapture": "",
              "allowAudioRecording": "",
              "prefillFromEntityProfile": "",
              "entityFieldName": "",
              "isEditable": "",
              "showQuestionInPreview": "",
              "deleted": "",
              "remarks": "",
              "value": "",
              "usedForScoring": "",
              "questionType": "",
              "canBeNotApplicable": "",
              "visibleIf": "",
              "validation": "",
              "externalId": "",
              "tip": "",
              "hint": "",
              "responseType": "pageQuestions",
              "modeOfCollection": "",
              "accessibility": "",
              "rubricLevel": "",
              "sectionHeader": "",
              "page": "p2",
              "questionNumber": "",
              "updatedAt": "",
              "createdAt": "",
              "__v": "",
              "createdFromQuestionId": "",
              "evidenceMethod": "",
              "payload": "",
              "startTime": "",
              "endTime": "",
              "gpsLocation": "",
              "file": "",
              "pageQuestions": [
                  {
                      "_id": "649c14e75c81330008b7e73f",
                      "question": [
                          "Years of Experience (Total years of experience in the service)",
                          "अनुभव के वर्ष (सेवा में अनुभव के कुल वर्ष)"
                      ],
                      "isCompleted": false,
                      "showRemarks": false,
                      "options": [],
                      "sliderOptions": [],
                      "children": [],
                      "questionGroup": [
                          "A1"
                      ],
                      "fileName": [],
                      "instanceQuestions": [],
                      "isAGeneralQuestion": false,
                      "autoCapture": false,
                      "allowAudioRecording": false,
                      "prefillFromEntityProfile": false,
                      "entityFieldName": "",
                      "isEditable": true,
                      "showQuestionInPreview": false,
                      "deleted": false,
                      "remarks": "",
                      "value": "",
                      "usedForScoring": "",
                      "questionType": "auto",
                      "canBeNotApplicable": "false",
                      "visibleIf": "",
                      "validation": {
                          "required": true,
                          "IsNumber": "true"
                      },
                      "externalId": "Q6_1687950555455-1687950567520",
                      "tip": "",
                      "hint": "",
                      "responseType": "number",
                      "modeOfCollection": "onfield",
                      "accessibility": "No",
                      "rubricLevel": "",
                      "sectionHeader": "",
                      "page": "p2",
                      "questionNumber": "6",
                      "updatedAt": "2023-06-28T11:09:27.614Z",
                      "createdAt": "2023-06-28T11:09:25.896Z",
                      "__v": 0,
                      "createdFromQuestionId": "649c14e55c81330008b7e612",
                      "evidenceMethod": "D1_1687950555455",
                      "payload": {
                          "criteriaId": "649c14e75c81330008b7e79c",
                          "responseType": "number",
                          "evidenceMethod": "D1_1687950555455",
                          "rubricLevel": ""
                      },
                      "startTime": 1694157617113,
                      "endTime": "",
                      "gpsLocation": "",
                      "file": ""
                  },
                  {
                      "_id": "649c14e75c81330008b7e740",
                      "question": [
                          "Which sport did you play in School/College?",
                          "जब आप स्कूल/कॉलेज थे तो  कौन सा खेल खेलते थे?"
                      ],
                      "isCompleted": false,
                      "showRemarks": false,
                      "options": [],
                      "sliderOptions": [],
                      "children": [],
                      "questionGroup": [
                          "A1"
                      ],
                      "fileName": [],
                      "instanceQuestions": [],
                      "isAGeneralQuestion": false,
                      "autoCapture": false,
                      "allowAudioRecording": false,
                      "prefillFromEntityProfile": false,
                      "entityFieldName": "",
                      "isEditable": true,
                      "showQuestionInPreview": false,
                      "deleted": false,
                      "remarks": "",
                      "value": "",
                      "usedForScoring": "",
                      "questionType": "auto",
                      "canBeNotApplicable": "false",
                      "visibleIf": "",
                      "validation": {
                          "required": true
                      },
                      "externalId": "Q7_1687950555455-1687950567521",
                      "tip": "",
                      "hint": "",
                      "responseType": "text",
                      "modeOfCollection": "onfield",
                      "accessibility": "No",
                      "rubricLevel": "",
                      "sectionHeader": "",
                      "page": "p2",
                      "questionNumber": "7",
                      "updatedAt": "2023-06-28T11:09:27.614Z",
                      "createdAt": "2023-06-28T11:09:25.907Z",
                      "__v": 0,
                      "createdFromQuestionId": "649c14e55c81330008b7e618",
                      "evidenceMethod": "D1_1687950555455",
                      "payload": {
                          "criteriaId": "649c14e75c81330008b7e79c",
                          "responseType": "text",
                          "evidenceMethod": "D1_1687950555455",
                          "rubricLevel": ""
                      },
                      "startTime": 1694157617117,
                      "endTime": "",
                      "gpsLocation": "",
                      "file": ""
                  },
                  {
                      "_id": "649c14e75c81330008b7e741",
                      "question": [
                          "To what competitive level do you have experience participating?",
                          "आपको किस-किस स्तर पर प्रतिस्पर्धा में भाग लेने का अनुभव प्राप्त है?"
                      ],
                      "isCompleted": false,
                      "showRemarks": false,
                      "options": [
                          {
                              "value": "R1",
                              "label": "District/जिला",
                              "score": 0
                          },
                          {
                              "value": "R2",
                              "label": "State/राज्य",
                              "score": 0
                          },
                          {
                              "value": "R3",
                              "label": "National/ राष्ट्रीय",
                              "score": 0
                          },
                          {
                              "value": "R4",
                              "label": "None/कोई नहीं",
                              "score": 0
                          }
                      ],
                      "sliderOptions": [],
                      "children": [],
                      "questionGroup": [
                          "A1"
                      ],
                      "fileName": [],
                      "instanceQuestions": [],
                      "isAGeneralQuestion": false,
                      "autoCapture": false,
                      "allowAudioRecording": false,
                      "prefillFromEntityProfile": false,
                      "entityFieldName": "",
                      "isEditable": true,
                      "showQuestionInPreview": false,
                      "deleted": false,
                      "remarks": "",
                      "value": "",
                      "usedForScoring": "",
                      "questionType": "auto",
                      "canBeNotApplicable": "false",
                      "visibleIf": "",
                      "validation": {
                          "required": true
                      },
                      "externalId": "Q8_1687950555455-1687950567521",
                      "tip": "",
                      "hint": "",
                      "responseType": "radio",
                      "modeOfCollection": "onfield",
                      "accessibility": "No",
                      "rubricLevel": "",
                      "sectionHeader": "",
                      "page": "p2",
                      "questionNumber": "8",
                      "updatedAt": "2023-06-28T11:09:27.614Z",
                      "createdAt": "2023-06-28T11:09:25.918Z",
                      "__v": 0,
                      "createdFromQuestionId": "649c14e55c81330008b7e61e",
                      "evidenceMethod": "D1_1687950555455",
                      "payload": {
                          "criteriaId": "649c14e75c81330008b7e79c",
                          "responseType": "radio",
                          "evidenceMethod": "D1_1687950555455",
                          "rubricLevel": ""
                      },
                      "startTime": 1694157617120,
                      "endTime": "",
                      "gpsLocation": "",
                      "file": ""
                  },
                  {
                      "_id": "649c14e75c81330008b7e742",
                      "question": [
                          "UIDSE of the school",
                          "स्कूल का यूआईडीएसई"
                      ],
                      "isCompleted": false,
                      "showRemarks": false,
                      "options": [],
                      "sliderOptions": [],
                      "children": [],
                      "questionGroup": [
                          "A1"
                      ],
                      "fileName": [],
                      "instanceQuestions": [],
                      "isAGeneralQuestion": false,
                      "autoCapture": false,
                      "allowAudioRecording": false,
                      "prefillFromEntityProfile": false,
                      "entityFieldName": "",
                      "isEditable": true,
                      "showQuestionInPreview": false,
                      "deleted": false,
                      "remarks": "",
                      "value": "",
                      "usedForScoring": "",
                      "questionType": "auto",
                      "canBeNotApplicable": "false",
                      "visibleIf": "",
                      "validation": {
                          "required": true
                      },
                      "externalId": "Q9_1687950555455-1687950567522",
                      "tip": "",
                      "hint": "",
                      "responseType": "text",
                      "modeOfCollection": "onfield",
                      "accessibility": "No",
                      "rubricLevel": "",
                      "sectionHeader": "",
                      "page": "p2",
                      "questionNumber": "9",
                      "updatedAt": "2023-06-28T11:09:27.614Z",
                      "createdAt": "2023-06-28T11:09:25.932Z",
                      "__v": 0,
                      "createdFromQuestionId": "649c14e55c81330008b7e624",
                      "evidenceMethod": "D1_1687950555455",
                      "payload": {
                          "criteriaId": "649c14e75c81330008b7e79c",
                          "responseType": "text",
                          "evidenceMethod": "D1_1687950555455",
                          "rubricLevel": ""
                      },
                      "startTime": 1694157617124,
                      "endTime": "",
                      "gpsLocation": "",
                      "file": ""
                  }
              ]
          }
      ],
      "name": "About the Teacher"
  }]}
}
